apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# the guide explicitly says to install to kube-system
namespace: kube-system

# This kustomization file deploys the NFS CSI driver and snapshot controller
resources:
  #  Pulled from https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.11.0/deploy/install-driver.sh
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.11.0/deploy/rbac-csi-nfs.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.11.0/deploy/csi-nfs-driverinfo.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.11.0/deploy/csi-nfs-controller.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.11.0/deploy/csi-nfs-node.yaml
  # Additional snapshotting resources from the same install script
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.11.0/deploy/crd-csi-snapshot.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.11.0/deploy/rbac-snapshot-controller.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.11.0/deploy/csi-snapshot-controller.yaml
