- name: Import ansible user
  ansible.builtin.import_tasks: ansible-user.yaml
- name: Import packages
  ansible.builtin.import_tasks: packages.yaml
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
- name: Install core packages
  ansible.builtin.package:
    name: "{{ core_packages }}"
    state: present
- name: Ensure rsync service is enabled and running
  ansible.builtin.service:
    name: rsync
    state: started
    enabled: true
