apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml

namespace: transmission

commonLabels:
  app.kubernetes.io/name: transmission
  app.kubernetes.io/component: bittorrent-client
  app.kubernetes.io/part-of: media-stack
