apiVersion: v1
kind: Secret
metadata:
  name: transmission-password
  namespace: transmission
  annotations:
    argocd.argoproj.io/sync-options: "Force=true,Replace=true"
    "k8s-secret-sync.weinbender.io/provider-name": "op"
    "k8s-secret-sync.weinbender.io/secret-key": "password"
    "k8s-secret-sync.weinbender.io/provider-ref": "op://microk8s/transmission/password"
type: Opaque
