apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vm-deployment.yaml
  - vm-service.yaml
  - vmagent-deployment.yaml
  - vmagent-service.yaml
  - vmagent-configmap.yaml
  - vm-httproute.yaml
