version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "terraform/mgmt"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/aws"
    schedule:
      interval: "weekly"
