apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-example
spec:
  hostnames:
    - my.example.com
  parentRefs:
    - name: cluster-gateway
      namespace: default
  targetRefs:
    - kind: Service
      name: argocd-server
      namespace: argocd
      port: 443
