apiVersion: v1
kind: Secret
metadata:
  name: infra-repo-secrets
  namespace: argocd
  annotations:
    "k8s-secrets-sync.weinbender.io/provider": "op"
    "k8s-secrets-sync.weinbender.io/secret-key": "sshPrivateKey"
    "k8s-secrets-sync.weinbender.io/ref": "op://microk8s/argocd-microk8s-ssh-pk/privateKey"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git@github.com:jackweinbender/infrastructure.git
  # sshPrivateKey: is the key that will be used to authenticate with the repository.
