apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cluster system resources
  sourceRepos:
    - git@github.com:jackweinbender/infrastructure.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cluster applications
  sourceRepos:
    - git@github.com:jackweinbender/infrastructure.git
  destinations:
    - namespace: "!kube-system"
      server: https://kubernetes.default.svc
    - namespace: "!default"
      server: https://kubernetes.default.svc
    - namespace: "!argocd"
      server: https://kubernetes.default.svc
