apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jackweinbender/infrastructure
    targetRevision: HEAD
    path: kubernetes/grafana-alloy
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - Prune=true
    automated:
      prune: true
      selfHeal: true
