apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jackweinbender/infrastructure
    targetRevision: main
    path: kubernetes/otel-operator
  destination:
    namespace: otel
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - Prune=true
    automated:
      prune: true
      selfHeal: true
