apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: infrastructure
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/jackweinbender/infrastructure
    targetRevision: HEAD
    path: kubernetes/redis
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Validate=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
