apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: signoz
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: signoz
    repoURL: https://charts.signoz.io
    targetRevision: 0.79.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - Prune=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
