apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: tailscale
  labels:
    app.kubernetes.io/name: tailscale
    app.kubernetes.io/managed-by: ArgoCD
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/tailscale
    repoURL: git@github.com:jackweinbender/infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
