apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twentycrm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: twentycrm
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/twentycrm
    repoURL: git@github.com:jackweinbender/infrastructure.git
    targetRevision: feature/add-twenty-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
