apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-secrets-sync
  namespace: k8s-secrets-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-secrets-sync
  template:
    metadata:
      labels:
        app: k8s-secrets-sync
    spec:
      serviceAccountName: k8s-secrets-sync-sa
      containers:
        - name: k8s-secrets-sync
          image: ghcr.io/jackweinbender/k8s-secrets-sync:latest
          env:
            - name: OP_SERVICE_ACCOUNT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: op-service-account-token
                  key: token
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
