apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: logs-collector
spec:
  serviceAccount: otel-collector
  mode: daemonset
  env:
    - name: GRAFANA_CLOUD_API_BEARER_TOKEN
      valueFrom:
        secretKeyRef:
          name: grafana-bearer-token
          key: token
  image: otel/opentelemetry-collector-contrib
  config:
    receivers:
      filelog:
        include_file_path: true
        include:
          - /var/log/pods/*/*/*.log
        operators:
          - id: container-parser
            type: container
    processors:
      resource/clusterName:
        attributes:
          - action: insert
            key: k8s.cluster.name
            value: "homelab"
    exporters:
      otlphttp/grafana:
        endpoint: "https://otlp-gateway-prod-us-east-0.grafana.net/otlp"
        headers:
          authorization: "Basic ${GRAFANA_CLOUD_API_BEARER_TOKEN}"
        tls:
          insecure: false
    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors:
            - resource/clusterName
          exporters:
            - otlphttp/grafana
