apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  env:
    - name: GRAFANA_CLOUD_API_KEY
      valueFrom:
        secretKeyRef:
          name: grafana-token
          key: token
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus/node-exporter:
        config:
          scrape_configs:
            - job_name: "node-exporter"
              scrape_interval: 60s
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - action: replace
                  source_labels: [__address__]
                  regex: "(.*):10250"
                  replacement: "$1:9100"
                  target_label: __address__
      prometheus/kubelet:
        config:
          scrape_configs:
            - job_name: "kubelet"
              scrape_interval: 60s
              scheme: https
              tls_config:
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - action: labelmap
                  regex: __meta_kubernetes_node_label_(.+)
              metrics_path: /metrics
      prometheus/ksm:
        config:
          scrape_configs:
            - job_name: "kube-state-metrics"
              scrape_interval: 120s
              static_configs:
                - targets:
                    ["kube-state-metrics.kube-system.svc.cluster.local:8080"]
    processors:
      filter/ksm:
        metrics:
          include:
            match_type: strict
            metric_names:
              - kube_pod_status_phase
              - kube_pod_status_ready
              - kube_pod_status_scheduled
              - kube_deployment_status_replicas
              - kube_deployment_status_replicas_available
              - kube_node_status_condition
              - kube_node_status_capacity_cpu_cores
              - kube_node_status_capacity_memory_bytes
              - kube_node_status_allocatable_cpu_cores
              - kube_node_status_allocatable_memory_bytes
      filter/kubelet:
        metrics:
          include:
            match_type: strict
            metric_names:
              - kubelet_running_pod_count
              - kubelet_runtime_operations_total
              - kubelet_runtime_operations_errors_total
              - kubelet_docker_operations_total
              - kubelet_docker_operations_errors_total
              - kubelet_docker_operations_latency_microseconds
              - kubelet_docker_operations_latency_microseconds_count
              - kubelet_docker_operations_latency_microseconds_sum
              - kubelet_pleg_relist_duration_seconds
              - kubelet_pleg_relist_interval_seconds
              - kubelet_pleg_relist_interval_seconds_count
              - kubelet_pleg_relist_interval_seconds_sum
              - kubelet_pleg_relist_duration_seconds_count
              - kubelet_pleg_relist_duration_seconds_sum
              - kubelet_pod_start_duration_seconds
              - kubelet_pod_worker_duration_seconds
              - kubelet_pod_worker_duration_seconds_count
              - kubelet_pod_worker_duration_seconds_sum
              - kubelet_pod_start_duration_seconds_count
              - kubelet_pod_start_duration_seconds_sum
              - kubelet_cgroup_manager_duration_seconds
              - kubelet_cgroup_manager_duration_seconds_count
              - kubelet_cgroup_manager_duration_seconds_sum
              - kubelet_containers_per_pod_count
              - kubelet_containers_per_pod_count_count
              - kubelet_containers_per_pod_count_sum
              - kubelet_evictions
              - kubelet_eviction_stats_age_seconds
              - kubelet_eviction_stats_age_seconds_count
              - kubelet_eviction_stats_age_seconds_sum
              - kubelet_node_config_error
              - kubelet_node_config_success
              - kubelet_node_config_active
              - kubelet_node_config_assigned
              - kubelet_node_config_last_known_good
              - kubelet_node_config_error_count
              - kubelet_node_config_success_count
              - kubelet_node_config_active_count
              - kubelet_node_config_assigned_count
              - kubelet_node_config_last_known_good_count
              - kubelet_node_config_error_sum
              - kubelet_node_config_success_sum
              - kubelet_node_config_active_sum
              - kubelet_node_config_assigned_sum
              - kubelet_node_config_last_known_good_sum
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      debug: {}
      otlphttp/grafana:
        endpoint: "https://otlp-gateway-prod-us-east-0.grafana.net/otlp"
        headers:
          authorization: "Basic ${GRAFANA_CLOUD_API_KEY}"
        tls:
          insecure: false

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        metrics:
          receivers:
            [otlp, prometheus/node-exporter, prometheus/kubelet, prometheus/ksm]
          #processors: [filter/kubelet, filter/ksm, memory_limiter, batch]
          processors: [memory_limiter, batch]
          exporters: [debug, otlphttp/grafana]
