apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: opentelemetry
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
    - name: otlp-grpc # Default endpoint for OpenTelemetry gRPC receiver
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlp-http # Default endpoint for OpenTelemetry HTTP receiver
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: metrics # Default endpoint for querying metrics
      port: 8888
      protocol: TCP
      targetPort: 8888
    - name: zpages # ZPages debugging interface
      port: 55679
      protocol: TCP
      targetPort: 55679
  # Additional receiver ports (uncomment if needed)
  # - name: jaeger-grpc # Jaeger gRPC receiver
  #   port: 14250
  #   protocol: TCP
  #   targetPort: 14250
  # - name: jaeger-http # Jaeger HTTP receiver
  #   port: 14268
  #   protocol: TCP
  #   targetPort: 14268
  # - name: zipkin # Zipkin receiver
  #   port: 9411
  #   protocol: TCP
  #   targetPort: 9411
  selector:
    app: opentelemetry
    component: otel-collector
