apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  env:
    - name: GRAFANA_CLOUD_API_KEY
      valueFrom:
        secretKeyRef:
          name: grafana-token
          key: token
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      hostmetrics:
        collection_interval: 60s
        scrapers:
          cpu: {}
          disk: {}
          memory: {}
      prometheus/kubelet:
        config:
          scrape_configs:
            - job_name: "kubelet"
              scrape_interval: 60s
              scheme: https
              tls_config:
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - action: labelmap
                  regex: __meta_kubernetes_node_label_(.+)
              metrics_path: /metrics
              metric_relabel_configs:
                # Drop even more high-cardinality metrics
                - source_labels: [__name__]
                  regex: "container_.+|kubelet_volume_stats_.+|kube_pod_container_.+|kube_pod_status_.+|kube_pod_info|kube_pod_labels|kube_node_status_.+|kube_node_info|kube_node_labels|kube_node_spec_.+|kube_node_status_.+|kube_deployment_status_.+|kube_deployment_spec_.+|kube_deployment_labels|kube_deployment_info|kube_namespace_labels|kube_namespace_status_.+|kube_namespace_info|kube_service_info|kube_service_labels|kube_service_spec_.+|kube_service_status_.+|kube_endpoint_.+|kube_replicaset_.+|kube_statefulset_.+|kube_daemonset_.+|kube_job_.+|kube_cronjob_.+|kube_replicationcontroller_.+|kube_secret_.+|kube_configmap_.+|kube_ingress_.+|kube_persistentvolume_.+|kube_persistentvolumeclaim_.+|kube_storageclass_.+|kube_horizontalpodautoscaler_.+|kube_certificate_.+|kube_controllerrevision_.+|kube_runtimeclass_.+|kube_priorityclass_.+|kube_resourcequota_.+|kube_limitrange_.+|kube_poddisruptionbudget_.+|kube_pod_owner|kube_pod_restart_policy|kube_pod_start_time|kube_pod_completion_time|kube_pod_deletion_timestamp|kube_pod_status_phase|kube_pod_status_ready|kube_pod_status_scheduled|kube_pod_status_unschedulable|kube_pod_status_initialized|kube_pod_status_reason|kube_pod_status_reason_unschedulable|kube_pod_status_reason_evicted|kube_pod_status_reason_failed|kube_pod_status_reason_oomkilled|kube_pod_status_reason_nodeaffinity|kube_pod_status_reason_podaffinity|kube_pod_status_reason_podantiaffinity|kube_pod_status_reason_tainttoleration|kube_pod_status_reason_toleration|kube_pod_status_reason_nodeunschedulable|kube_pod_status_reason_nodeaffinityunsatisfiable|kube_pod_status_reason_podaffinityunsatisfiable|kube_pod_status_reason_podantiaffinityunsatisfiable|kube_pod_status_reason_tainttolerationunsatisfiable|kube_pod_status_reason_tolerationunsatisfiable|kube_pod_status_reason_nodeunschedulableunsatisfiable|kube_pod_status_reason_nodeaffinityunsatisfiableunsatisfiable|kube_pod_status_reason_podaffinityunsatisfiableunsatisfiable|kube_pod_status_reason_podantiaffinityunsatisfiableunsatisfiable|kube_pod_status_reason_tainttolerationunsatisfiableunsatisfiable|kube_pod_status_reason_tolerationunsatisfiableunsatisfiable|kube_pod_status_reason_nodeunschedulableunsatisfiableunsatisfiable|kube_pod_status_reason_nodeaffinityunsatisfiableunsatisfiableunsatisfiable|kube_pod_status_reason_podaffinityunsatisfiableunsatisfiableunsatisfiable|kube_pod_status_reason_podantiaffinityunsatisfiableunsatisfiableunsatisfiable|kube_pod_status_reason_tainttolerationunsatisfiableunsatisfiableunsatisfiable|kube_pod_status_reason_tolerationunsatisfiableunsatisfiableunsatisfiable|kube_pod_status_reason_nodeunschedulableunsatisfiableunsatisfiableunsatisfiable"
                  action: drop
      prometheus/ksm:
        config:
          scrape_configs:
            - job_name: "kube-state-metrics"
              scrape_interval: 60s
              static_configs:
                - targets:
                    ["kube-state-metrics.kube-system.svc.cluster.local:8080"]
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      debug: {}
      otlphttp/grafana:
        endpoint: "https://otlp-gateway-prod-us-east-0.grafana.net/otlp"
        headers:
          authorization: "Basic ${GRAFANA_CLOUD_API_KEY}"
        tls:
          insecure: false

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        metrics:
          receivers: [otlp, hostmetrics, prometheus/kubelet, prometheus/ksm]
          processors: [memory_limiter, batch]
          exporters: [debug, otlphttp/grafana]
