apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  serviceAccount: otel-collector
  env:
    - name: GRAFANA_CLOUD_API_BEARER_TOKEN
      valueFrom:
        secretKeyRef:
          name: grafana-bearer-token
          key: token
    - name: GRAFANA_CLOUD_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: grafana-token
          key: token
    - name: PROMETHEUS_USERNAME
      value: "933879"
    - name: PROMETHEUS_URL
      value: "https://prometheus-prod-13-prod-us-east-0.grafana.net"
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: integrations/kubernetes/cadvisor
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
                server_name: kubernetes
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - target_label: __address__
                  replacement: kubernetes.default.svc.cluster.local:443
                - source_labels: [__meta_kubernetes_node_name]
                  regex: (.+)
                  replacement: /api/v1/nodes/$${1}/proxy/metrics/cadvisor
                  target_label: __metrics_path__
              metric_relabel_configs:
                - source_labels: [__name__]
                  action: keep
                  regex: container_cpu_cfs_periods_total|container_cpu_cfs_throttled_periods_total|container_cpu_usage_seconds_total|container_fs_reads_bytes_total|container_fs_reads_total|container_fs_writes_bytes_total|container_fs_writes_total|container_memory_cache|container_memory_rss|container_memory_swap|container_memory_working_set_bytes|container_network_receive_bytes_total|container_network_receive_packets_dropped_total|container_network_receive_packets_total|container_network_transmit_bytes_total|container_network_transmit_packets_dropped_total|container_network_transmit_packets_total|machine_memory_bytes
            - job_name: integrations/kubernetes/kubelet
              scheme: https
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
                server_name: kubernetes
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - target_label: __address__
                  replacement: kubernetes.default.svc.cluster.local:443
                - source_labels: [__meta_kubernetes_node_name]
                  regex: (.+)
                  replacement: /api/v1/nodes/$${1}/proxy/metrics
                  target_label: __metrics_path__
              metric_relabel_configs:
                - source_labels: [__name__]
                  action: keep
                  regex: go_goroutines|kubelet_certificate_manager_client_expiration_renew_errors|kubelet_certificate_manager_client_ttl_seconds|kubelet_certificate_manager_server_ttl_seconds|kubelet_cgroup_manager_duration_seconds_bucket|kubelet_cgroup_manager_duration_seconds_count|kubelet_node_config_error|kubelet_node_name|kubelet_pleg_relist_duration_seconds_bucket|kubelet_pleg_relist_duration_seconds_count|kubelet_pleg_relist_interval_seconds_bucket|kubelet_pod_start_duration_seconds_bucket|kubelet_pod_start_duration_seconds_count|kubelet_pod_worker_duration_seconds_bucket|kubelet_pod_worker_duration_seconds_count|kubelet_running_container_count|kubelet_running_containers|kubelet_running_pod_count|kubelet_running_pods|kubelet_runtime_operations_errors_total|kubelet_runtime_operations_total|kubelet_server_expiration_renew_errors|kubelet_volume_stats_available_bytes|kubelet_volume_stats_capacity_bytes|kubelet_volume_stats_inodes|kubelet_volume_stats_inodes_free|kubelet_volume_stats_inodes_used|kubelet_volume_stats_used_bytes|kubernetes_build_info|namespace_workload_pod|process_cpu_seconds_total|process_resident_memory_bytes|rest_client_requests_total|storage_operation_duration_seconds_count|storage_operation_errors_total|volume_manager_total_volumes
            - job_name: integrations/kubernetes/kube-state-metrics
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels:
                    [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                  action: keep
                  regex: kube-state-metrics
              metric_relabel_configs:
                - source_labels: [__name__]
                  action: keep
                  regex: kube_configmap_info|kube_configmap_metadata_resource_version|kube_daemonset.*|kube_deployment_metadata_generation|kube_deployment_spec_replicas|kube_deployment_status_condition|kube_deployment_status_observed_generation|kube_deployment_status_replicas_available|kube_deployment_status_replicas_updated|kube_horizontalpodautoscaler_spec_max_replicas|kube_horizontalpodautoscaler_spec_min_replicas|kube_horizontalpodautoscaler_status_current_replicas|kube_horizontalpodautoscaler_status_desired_replicas|kube_job.*|kube_namespace_status_phase|kube_node.*|kube_persistentvolume_status_phase|kube_persistentvolumeclaim_access_mode|kube_persistentvolumeclaim_info|kube_persistentvolumeclaim_labels|kube_persistentvolumeclaim_resource_requests_storage_bytes|kube_persistentvolumeclaim_status_phase|kube_pod_container_info|kube_pod_container_resource_limits|kube_pod_container_resource_requests|kube_pod_container_status_last_terminated_reason|kube_pod_container_status_restarts_total|kube_pod_container_status_waiting_reason|kube_pod_info|kube_pod_owner|kube_pod_spec_volumes_persistentvolumeclaims_info|kube_pod_start_time|kube_pod_status_phase|kube_pod_status_reason|kube_replicaset.*|kube_resourcequota|kube_secret_metadata_resource_version|kube_statefulset.*
            - job_name: integrations/node_exporter
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels:
                    [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                  action: keep
                  regex: prometheus-node-exporter.*
                - source_labels: [__meta_kubernetes_pod_node_name]
                  target_label: instance
                - source_labels: [__meta_kubernetes_namespace]
                  target_label: namespace
              metric_relabel_configs:
                - source_labels: [__name__]
                  action: keep
                  regex: node_cpu.*|node_exporter_build_info|node_filesystem.*|node_memory.*|node_network_receive_bytes_total|node_network_receive_drop_total|node_network_transmit_bytes_total|node_network_transmit_drop_total|process_cpu_seconds_total|process_resident_memory_bytes
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
      attributes/add_cluster:
        actions:
          - key: k8s.cluster.name
            value: homelab
            action: upsert
          - key: cluster
            value: homelab
            action: upsert

    exporters:
      debug: {}
      otlphttp/grafana:
        endpoint: "https://otlp-gateway-prod-us-east-0.grafana.net/otlp"
        headers:
          authorization: "Basic ${GRAFANA_CLOUD_API_BEARER_TOKEN}"
        tls:
          insecure: false
      prometheusremotewrite/grafanaCloudMetrics:
        external_labels:
          cluster: "homelab"
          k8s.cluster.name: "homelab"
        endpoint: "https://${PROMETHEUS_USERNAME}:${GRAFANA_CLOUD_API_TOKEN}@${PROMETHEUS_URL}/api/prom/push"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        metrics:
          receivers: [otlp, prometheus]
          processors:
            - attributes/add_cluster
            - memory_limiter
            - batch
          exporters: [debug, otlphttp/grafana]
