apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  env:
    - name: GRAFANA_CLOUD_API_KEY
      valueFrom:
        secretKeyRef:
          name: grafana-token
          key: token
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      hostmetrics:
        collection_interval: 60s
        scrapers:
          cpu: {}
          disk: {}
          memory: {}
      prometheus/kubelet:
        config:
          scrape_configs:
            - job_name: "kubelet"
              scrape_interval: 60s
              scheme: https
              tls_config:
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - action: labelmap
                  regex: __meta_kubernetes_node_label_(.+)
              metrics_path: /metrics
              metric_relabel_configs:
                # Drop high-cardinality metrics (example: container_fs_inodes_free)
                - source_labels: [__name__]
                  regex: "container_fs_inodes_free|container_fs_inodes_total|container_fs_usage_bytes|container_fs_limit_bytes|container_fs_reads_bytes_total|container_fs_writes_bytes_total|container_fs_reads_total|container_fs_writes_total|container_network_receive_bytes_total|container_network_transmit_bytes_total|container_network_receive_packets_total|container_network_transmit_packets_total|container_network_receive_errors_total|container_network_transmit_errors_total"
                  action: drop
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      debug: {}
      otlphttp/grafana:
        endpoint: "https://otlp-gateway-prod-us-east-0.grafana.net/otlp"
        headers:
          authorization: "Basic ${GRAFANA_CLOUD_API_KEY}"
        tls:
          insecure: false

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        metrics:
          receivers: [otlp, hostmetrics, prometheus/kubelet]
          processors: [memory_limiter, batch]
          exporters: [debug, otlphttp/grafana]
