apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  env:
    - name: GRAFANA_CLOUD_API_KEY
      valueFrom:
        secretKeyRef:
          name: grafana-token
          key: token
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus/node-exporter:
        config:
          scrape_configs:
            - job_name: "node-exporter"
              scrape_interval: 60s
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - action: replace
                  source_labels: [__address__]
                  regex: "(.*):10250"
                  replacement: "$1:9100"
                  target_label: __address__
      prometheus/ksm:
        config:
          scrape_configs:
            - job_name: "kube-state-metrics"
              scrape_interval: 120s
              static_configs:
                - targets:
                    ["kube-state-metrics.kube-system.svc.cluster.local:8080"]
    processors:
      filter/ksm:
        metrics:
          include:
            match_type: strict
            metric_names:
              - kube_pod_status_phase
              - kube_pod_status_ready
              - kube_pod_status_scheduled
              - kube_deployment_status_replicas
              - kube_deployment_status_replicas_available
              - kube_node_status_condition
              - kube_node_status_capacity_cpu_cores
              - kube_node_status_capacity_memory_bytes
              - kube_node_status_allocatable_cpu_cores
              - kube_node_status_allocatable_memory_bytes

      filter/node_exporter:
        metrics:
          include:
            match_type: strict
            metric_names:
              # Basic node health and resource usage
              - node_cpu_seconds_total
              - node_memory_MemAvailable_bytes
              - node_memory_MemTotal_bytes
              - node_memory_MemFree_bytes
              - node_memory_Buffers_bytes
              - node_memory_Cached_bytes
              - node_load1
              - node_load5
              - node_load15
              - node_filesystem_size_bytes
              - node_filesystem_free_bytes
              - node_filesystem_avail_bytes
              - node_filesystem_readonly
              - node_network_receive_bytes_total
              - node_network_transmit_bytes_total
              - node_network_receive_errs_total
              - node_network_transmit_errs_total
              - node_disk_read_bytes_total
              - node_disk_written_bytes_total
              - node_disk_reads_completed_total
              - node_disk_writes_completed_total
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      debug: {}
      otlphttp/grafana:
        endpoint: "https://otlp-gateway-prod-us-east-0.grafana.net/otlp"
        headers:
          authorization: "Basic ${GRAFANA_CLOUD_API_KEY}"
        tls:
          insecure: false

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        metrics:
          receivers: [otlp, prometheus/node-exporter, prometheus/ksm]
          processors:
            - filter/node_exporter
            - filter/ksm
            - memory_limiter
            - batch
          exporters: [debug, otlphttp/grafana]
