apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml
  - collector-metrics.yaml
  - collector-logs.yaml
  - node_exporter.yaml
  - secrets.yaml
  - rbac.yaml
