apiVersion: v1
kind: Secret
metadata:
  name: grafana-otlp-headers
  annotations:
    argocd.argoproj.io/sync-options: "Force=true,Replace=true"
    "k8s-secrets-sync.weinbender.io/provider": "op"
    "k8s-secrets-sync.weinbender.io/secret-key": "headers"
    "k8s-secrets-sync.weinbender.io/ref": "op://microk8s/grafana-cloud-tokens/otlp-headers"
type: Opaque
