- name: Import nginx
  ansible.builtin.import_tasks: nginx.yaml
- name: Import certbot
  ansible.builtin.import_tasks: certbot.yaml
- name: Configure log rotation for nginx logs
  ansible.builtin.copy:
    src: logrotate-nginx
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root
    mode: "0644"
