- name: install nginx
  apt:
    name: nginx
    state: latest
    cache_valid_time: 3600
- name: update nginx configs
  synchronize:
    src: sites-enabled/
    dest: /etc/nginx/sites-enabled
    delete: true
- name: enable nginx service
  service:
    name: nginx
    state: started
    enabled: true
  notify: restart nginx
