- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    cache_valid_time: 3600
- name: Update nginx configs
  ansible.posix.synchronize:
    src: sites-available/
    dest: /etc/nginx/sites-enabled/
    delete: true
- name: Enable nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  notify: Restart nginx
