- name: add apt repo
  block:
    - name: get signing key
      become: true
      get_url:
        url: https://pkgs.tailscale.com/stable/{{ ansible_distribution|lower}}/{{ ansible_distribution_release }}.asc
        dest: /etc/apt/keyrings/tailscale.asc
        mode: "0644"
        force: true
    - name: add apt repo
      become: true
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/tailscale.asc] https://pkgs.tailscale.com/stable/{{ ansible_distribution|lower}} {{ ansible_distribution_release }} main"
        filename: tailscale
        state: present

- name: install cli
  become: true
  apt:
    name: tailscale
    state: latest
    cache_valid_time: 3600
