apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
  labels:
    app: immich-server
    component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
      component: server
  template:
    metadata:
      labels:
        app: immich-server
        component: server
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101000
        runAsGroup: 110000
        fsGroup: 110000
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:release
          ports:
            - containerPort: 2283
              name: http
          envFrom:
            - configMapRef:
                name: immich-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-database-password
                  key: password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-redis-auth
                  key: password
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"
          volumeMounts:
            - name: upload-storage
              mountPath: /usr/src/app/upload
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
          livenessProbe:
            httpGet:
              path: /api/server-info/ping
              port: 2283
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/server-info/ping
              port: 2283
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: upload-storage
          hostPath:
            path: /home/nas/media/immich/upload
            type: DirectoryOrCreate
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
