apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - configmap.yaml
  - secrets.yaml
  - deployment-server.yaml
  - deployment-ml.yaml
  - service-server.yaml
  - service-ml.yaml
  - httproute.yaml

commonLabels:
  app.kubernetes.io/name: immich
  app.kubernetes.io/part-of: immich
