# S3 backup credentials - managed via 1Password
apiVersion: v1
kind: Secret
metadata:
  name: s3-backup-credentials
  namespace: postgresql
  annotations:
    argocd.argoproj.io/sync-options: "Replace=true"
    "k8s-secrets-sync.weinbender.io/provider": "op"
    "k8s-secrets-sync.weinbender.io/secret-key": "access-key-id"
    "k8s-secrets-sync.weinbender.io/ref": "op://microk8s/s3-backup-credentials/access-key-id"
type: Opaque
stringData:
  # access-key-id: managed by 1Password operator
---
# S3 backup secret access key - managed via 1Password
apiVersion: v1
kind: Secret
metadata:
  name: s3-backup-secret-key
  namespace: postgresql
  annotations:
    argocd.argoproj.io/sync-options: "Replace=true"
    "k8s-secrets-sync.weinbender.io/provider": "op"
    "k8s-secrets-sync.weinbender.io/secret-key": "secret-access-key"
    "k8s-secrets-sync.weinbender.io/ref": "op://microk8s/s3-backup-credentials/secret-access-key"
type: Opaque
stringData:
  # secret-access-key: managed by 1Password operator
