apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - postgresql-deployment.yaml
  - postgresql-service.yaml

configMapGenerator:
  - name: postgresql-config
    literals:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
  - name: postgresql-init
    files:
      - config/init.sql
  - name: postgresql-conf
    files:
      - config/postgresql.conf

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: pgvector/pgvector
    newTag: pg16
