apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: postgresql
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      securityContext:
        # Set fsGroup to ensure volumes have correct group ownership for NFS
        fsGroup: 110000
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          securityContext:
            # pgAdmin runs as user 5050 by default, which works well
            # We just need to ensure the volume has correct permissions via init container
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 80
              name: http
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-password
                  key: password
            - name: PGADMIN_CONFIG_SERVER_MODE
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: PGADMIN_CONFIG_SERVER_MODE
            - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /misc/ping
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /misc/ping
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: pgadmin-data
          hostPath:
            path: /home/nas/shared/pvcs/pgadmin-data
