# PostgreSQL database password - managed via 1Password
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-password
  namespace: postgresql
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
    "k8s-secret-sync.weinbender.io/provider-name": "op"
    "k8s-secret-sync.weinbender.io/secret-key": "password"
    "k8s-secret-sync.weinbender.io/provider-ref": "op://microk8s/postgresql-db/password"
type: Opaque
stringData:
  # password: managed by 1Password operator
