# PostgreSQL database password - managed via 1Password
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-password
  namespace: postgresql
  annotations:
    argocd.argoproj.io/sync-options: "Replace=true"
    "k8s-secrets-sync.weinbender.io/provider": "op"
    "k8s-secrets-sync.weinbender.io/secret-key": "password"
    "k8s-secrets-sync.weinbender.io/ref": "op://microk8s/postgresql-db/password"
type: Opaque
stringData:
  # password: managed by 1Password operator
