apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-wildcard
  namespace: cert-manager
spec:
  secretName: cluster-wildcard-tls
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - "*.k8s.weinbender.io"
    - k8s.weinbender.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
