apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml

namespace: sonarr

commonLabels:
  app.kubernetes.io/name: sonarr
  app.kubernetes.io/component: pvr
  app.kubernetes.io/part-of: media-stack
