apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
  labels:
    app: redis
data:
  redis.conf: |
    # Basic configuration
    bind 0.0.0.0
    port 6379

    # Memory configuration
    maxmemory 512mb
    maxmemory-policy allkeys-lru

    # Database configuration
    databases 16

    # Security - Require AUTH
    protected-mode yes

    # ACL configuration file
    aclfile /etc/redis/users.acl

    # Persistence (optional - for data durability)
    save 900 1
    save 300 10
    save 60 10000

    # Logging
    loglevel notice

  users.acl: |
    user default off
    user admin on >${ADMIN_PASSWORD} ~* &* +@all
    user immich on >${IMMICH_PASSWORD} ~* &* +@all|0
