apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis

resources:
  - configmap.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: redis
  app.kubernetes.io/part-of: infrastructure
