apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      securityContext:
        # these settings ensure that homeassistant runs with the correct user and group IDs
        # which are necessary for file permissions on the host system
        runAsNonRoot: true
        runAsUser: 101000
        runAsGroup: 110000
        fsGroup: 110000
      initContainers:
        - name: git-sync
          image: alpine/git:latest
          env:
            - name: HOME
              value: /tmp
          command: ["/bin/sh", "/usr/local/bin/git-sync.sh"]
          volumeMounts:
            - name: ha-config
              mountPath: /config
            - name: ssh-key
              mountPath: /etc/git-secret
              readOnly: true
            - name: git-sync-script
              mountPath: /usr/local/bin/git-sync.sh
              subPath: git-sync.sh
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:stable
          env:
            - name: GIT_SSH_COMMAND
              value: "ssh -i /etc/git-secret/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: ha-config
              mountPath: /config
            - name: ssh-key
              mountPath: /etc/git-secret
              readOnly: true
      volumes:
        - name: ha-config
          hostPath:
            path: /home/nas/shared/pvcs/homeassistant/config
            type: DirectoryOrCreate
        - name: ssh-key
          secret:
            secretName: github-pull-key
            defaultMode: 0440
        - name: git-sync-script
          configMap:
            name: git-sync-script
            defaultMode: 0755
