apiVersion: v1
kind: Secret
metadata:
  name: github-pull-key
  annotations:
    argocd.argoproj.io/sync-options: "Force=true,Replace=true"
    "k8s-secret-sync.weinbender.io/provider-name": "op"
    "k8s-secret-sync.weinbender.io/secret-key": "id_ed25519"
    "k8s-secret-sync.weinbender.io/provider-ref": "op://microk8s/github-private-key/privateKey"
type: Opaque
