name: "Terraform Plan & Apply"
description: "Terraform plan and apply for a Component / Subdirectory"

inputs:
  component:
    description: "Component / Subdirectory Name"
    required: true
  apply:
    description: "Apply the plan as a part of this action?"
    default: "false"
  skip_fmt:
    description: "Skip terraform fmt?"
    default: "false"
  skip_validate:
    description: "Skip terraform validate?"
    default: "false"

runs:
  using: composite
  steps:
    - name: Load secret
      uses: 1password/load-secrets-action@v2
      with:
        export-env: true
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SA_TOKEN }}
      run: |
        op inject \
          -i terraform/${{ inputs.component }}/terraform.tfvars.tmpl \
          -o terraform/${{ inputs.component }}/terraform.tfvars
    - uses: hashicorp/setup-terraform@v2
    # We always run init.
    - name: Terraform init
      id: init
      shell: bash
      run: terraform -chdir=terraform/${{ inputs.component }} init

    #  Skippables. Usually we should run them, though.
    - name: Terraform fmt
      if: ${{ inputs.skip_fmt != 'true' }}
      id: fmt
      shell: bash
      run: terraform -chdir=terraform/${{ inputs.component }} fmt -check
    - name: Terraform validate
      if: ${{ inputs.skip_validate != 'true' }}
      id: validate
      shell: bash
      run: terraform -chdir=terraform/${{ inputs.component }} validate

    # We always run plan.
    - name: Terraform plan
      id: plan
      shell: bash
      run: terraform -chdir=terraform/${{ inputs.component }} plan

    # DANGER: Only apply when explicitly instructed.
    - name: Terraform apply
      if: ${{ inputs.apply == 'true' }}
      id: apply
      shell: bash
      run: terraform -chdir=terraform/${{ inputs.component }} apply -auto-approve
