apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: tailscale
  annotations:
    secrets-operator.weinbender.io/provider: "op"
    secrets-operator.weinbender.io/secretDataKey: "TS_AUTHKEY"
    secrets-operator.weinbender.io/ref: "op://microk8s/ts-serviceaccount-key/credential"
type: Opaque
