apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: tailscale
  annotations:
    "k8s-secret-sync.weinbender.io/provider": "op"
    "k8s-secret-sync.weinbender.io/secret-key": "TS_AUTHKEY"
    "k8s-secret-sync.weinbender.io/ref": "op://microk8s/ts-serviceaccount-key/credential"
type: Opaque
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: tailscale
rules:
  - apiGroups: [""]
    resourceNames: ["tailscale-auth"]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: tailscale
subjects:
  - kind: ServiceAccount
    name: tailscale
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
