apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twentycrm-db
  name: twentycrm-db
  namespace: twentycrm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: twentycrm-db
  template:
    metadata:
      labels:
        app: twentycrm-db
    spec:
      securityContext:
        runAsUser: 101000
        runAsGroup: 110000
        fsGroup: 110000
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              chown -R 101000:110000 /var/lib/postgresql/data
              chmod 750 /var/lib/postgresql/data
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: twentycrm-db-data
      volumes:
        - name: twentycrm-db-data
          hostPath:
            path: /home/nas/shared/pvcs/twentycrm-db
            type: DirectoryOrCreate
      containers:
        - name: twentycrm-db
          image: pgvector/pgvector:pg16
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twentycrm-db-password
                  key: password
            - name: POSTGRES_DB
              value: "twentycrm"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
              name: tcp
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: twentycrm-db-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
