apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twentycrm-worker
  name: twentycrm-worker
  namespace: twentycrm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: twentycrm-worker
  template:
    metadata:
      labels:
        app: twentycrm-worker
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 110000
      volumes:
        # Server-specific data: file uploads, user data, application state
        - name: twentycrm-server-data
          hostPath:
            path: /home/nas/shared/pvcs/twentycrm-server
            type: DirectoryOrCreate
        # General application data: temporary files, logs, build artifacts
        - name: twentycrm-docker-data
          hostPath:
            path: /home/nas/shared/pvcs/twentycrm-docker
            type: DirectoryOrCreate
      containers:
        - name: twentycrm
          image: twentycrm/twenty:latest
          imagePullPolicy: Always
          env:
            - name: SERVER_URL
              value: "https://twentycrm.k8s.weinbender.io:443"
            - name: POSTGRES_ADMIN_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: PG_DATABASE_URL
              value: "postgres://$(POSTGRES_ADMIN_USER):$(POSTGRES_PASSWORD)@postgresql.postgresql.svc:5432/twentycrm"
            - name: DISABLE_DB_MIGRATIONS
              value: "true" # migrations should only run on the server
            - name: IS_SIGN_UP_DISABLED
              value: "false"
            - name: TELEMETRY_ENABLED
              value: "false"
            - name: STORAGE_TYPE
              value: "local"
            - name: REDIS_URL
              value: "redis://twentycrm-redis.twentycrm.svc:6379"
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: tokens
                  key: accessToken
          command:
            - yarn
            - worker:prod
          resources:
            requests:
              memory: "1024Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          stdin: true
          tty: true
          volumeMounts:
            # General application data storage
            - mountPath: /app/docker-data
              name: twentycrm-docker-data
            # Server-specific data: file uploads, user data
            - mountPath: /app/packages/twenty-server/.local-storage
              name: twentycrm-server-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
