apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twentycrm-server
  name: twentycrm-server
  namespace: twentycrm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: twentycrm-server
  template:
    metadata:
      labels:
        app: twentycrm-server
    spec:
      securityContext:
        fsGroup: 110000
      volumes:
        # Server-specific data: file uploads, user data, application state
        - name: twentycrm-server-data
          hostPath:
            path: /home/nas/shared/pvcs/twentycrm-server
            type: DirectoryOrCreate
        # General application data: temporary files, logs, build artifacts
        - name: twentycrm-docker-data
          hostPath:
            path: /home/nas/shared/pvcs/twentycrm-docker
            type: DirectoryOrCreate
      containers:
        - name: twentycrm
          image: twentycrm/twenty:latest
          imagePullPolicy: Always
          env:
            - name: NODE_PORT
              value: "3000"
            - name: SERVER_URL
              value: "https://app.twentycrm.k8s.weinbender.io:443"
            - name: POSTGRES_ADMIN_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: PG_DATABASE_URL
              value: "postgres://$(POSTGRES_ADMIN_USER):$(POSTGRES_PASSWORD)@postgresql.postgresql.svc:5432/twentycrm"
            - name: REDIS_URL
              value: "redis://twentycrm-redis.twentycrm.svc:6379"
            - name: DISABLE_DB_MIGRATIONS
              value: "false"
            - name: DEBUG_MODE
              value: "true"
            - name: LOG_LEVEL
              value: "debug"
            - name: IS_SIGN_UP_DISABLED
              value: "false"
            - name: IS_MULTIWORKSPACE_ENABLED
              value: "true"
            - name: TELEMETRY_ENABLED
              value: "false"
            - name: SIGN_IN_PREFILLED
              value: "false"
            - name: STORAGE_TYPE
              value: "local"
            - name: ACCESS_TOKEN_EXPIRES_IN
              value: "7d"
            - name: LOGIN_TOKEN_EXPIRES_IN
              value: "1h"
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: tokens
                  key: accessToken
          ports:
            - containerPort: 3000
              name: http-tcp
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          stdin: true
          tty: true
          volumeMounts:
            # General application data storage
            - mountPath: /app/docker-data
              name: twentycrm-docker-data
            # Server-specific data: file uploads, user data
            - mountPath: /app/packages/twenty-server/.local-storage
              name: twentycrm-server-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
