apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: jellyfin
  namespace: external-services
spec:
  endpoints:
    - fqdn:
        hostname: jellyfin.lxc.weinbender.io
        port: 8096
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: jellyfin
spec:
  hostnames:
    - jellyfin.k8s.weinbender.io
  parentRefs:
    - kind: Gateway
      name: cluster-gateway
      namespace: cluster-gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - kind: Backend
          name: jellyfin
          namespace: external-services
          port: 8096
          group: ""
          weight: 1
