apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: k8s-monitoring
    repo: "https://grafana.github.io/helm-charts"
    version: 3.4.0
    releaseName: k8s-monitoring
    namespace: grafana
    valuesFile: values.yaml
