name: "Ansible"

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SA_TOKEN }}
          VAULT_PASSWORD: op://network/AnsibleVault/password
      - name: Print masked secret
        run: echo $VAULT_PASSWORD > 'ansible/vault-password.secret'
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          working_directory: ansible
