name: "Ansible Playbook"

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"

defaults:
  run:
    working-directory: ./ansible

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SA_TOKEN }}
          TS_OAUTH_CLIENT_ID: "op://network/TailscaleOAuth/client-id"
          TS_OAUTH_CLIENT_SECRET: "op://network/TailscaleOAuth/client-secret"
          VAULT_PASSWORD: op://network/AnsibleVault/password
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: $TS_OAUTH_CLIENT_ID
          oauth-secret: $TS_OAUTH_CLIENT_SECRET
          tags: tag:ci
          version: 1.76.1
      - name: Set vault password file
        run: echo $VAULT_PASSWORD > 'vault-password.secret'
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt
            **/ansible-requirements.yaml
      - run: pip install -r requirements.txt
      - run: ansible-galaxy install -r ansible-requirements.yaml
      - run: ansible-lint
      - run: ansible-playbook -i inventory.yaml edge.yaml
