name: "Ansible Lint"

on:
  pull_request:
    paths:
      - "ansible/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SA_TOKEN }}
          VAULT_PASSWORD: op://network/AnsibleVault/password
      - name: Print masked secret
        run: echo $VAULT_PASSWORD > 'ansible/vault-password.secret'
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip" # caching pip dependencies
      - run: pip install ansible-core
      - run: ansible-galaxy install -r ansible/requirements.yaml
