name: "Ansible Lint"

on:
  pull_request:
    paths:
      - "ansible/**"

defaults:
  run:
    working-directory: ./ansible

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SA_TOKEN }}
          TS_OAUTH_CLIENT_ID: "op://network/TailscaleOAuth/client-id"
          TS_OAUTH_CLIENT_SECRET: "op://network/TailscaleOAuth/client-secret"
          GHA_SSH_KEY: "op://network/GithubActionsSSH/private key"
          VAULT_PASSWORD: op://network/AnsibleVault/password
      - name: Set vault password file
        run: echo $VAULT_PASSWORD > 'vault-password.secret'
      # - name: Set up ssh
      #   run: |
      #     mkdir -p ~/.ssh/
      #     chmod 0700 ~/.ssh
      #     eval $(ssh-agent -s)
      #     ssh-add <(echo "$GHA_SSH_KEY")
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: $TS_OAUTH_CLIENT_ID
          oauth-secret: $TS_OAUTH_CLIENT_SECRET
          tags: tag:ci
          version: 1.76.1
      - name: netmap
        run: tailscale status
      - run: ping -c 4 pi-scale.tortoise-noodlefish.ts.net
      - run: echo "testing123" > file.txt && scp -o StrictHostKeyChecking=no file.txt ansible@pi-scale.tortoise-noodlefish.ts.net:/home/ansible/test.txt
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.13"
      #     cache: "pip"
      # - run: pip install -r requirements.txt
      # - run: ansible-galaxy install -r ansible-requirements.yaml
      # - run: ansible-lint
      # - run: ansible-playbook --key-file=ssh.key -i inventory.yaml edge.yaml
