name: "Ansible Lint"

on:
  pull_request:
    paths:
      - "ansible/**"

defaults:
  run:
    working-directory: ./ansible

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:ci
      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SA_TOKEN }}
          VAULT_PASSWORD: op://network/AnsibleVault/password
      - name: Set vault password file
        run: echo $VAULT_PASSWORD > 'vault-password.secret'
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: ansible-galaxy install -r ansible-requirements.yaml
      - run: ansible-lint
      - run: ansible-playbook -i inventory.yaml edge.yaml
