apiVersion: apps/v1
kind: Deployment
metadata:
  name: twenty
  namespace: twenty
  labels:
    app: twenty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twenty
  template:
    metadata:
      labels:
        app: twenty
    spec:
      securityContext:
        fsGroup: 110000
      containers:
        - name: twenty
          image: twentycrm/twenty:latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: POSTGRES_ADMIN_USER
              value: "postgres"
            - name: POSTGRES_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: PG_DATABASE_URL
              value: "postgres://$(POSTGRES_ADMIN_USER):$(POSTGRES_ADMIN_PASSWORD)@postgresql.postgresql.svc.cluster.local:5432/twenty"
            - name: FRONT_BASE_URL
              value: "https://twenty.weinbender.io"
            - name: SERVER_URL
              value: "https://twenty.weinbender.io:443"
          volumeMounts:
            - name: twenty-data
              mountPath: /app/.local-storage
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: twenty-data
          hostPath:
            path: /home/nas/shared/pvcs/twenty
            type: DirectoryOrCreate
